### ISSUE TITLE
Exception in twitter stream

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/mage#8]
In the mage log, there are instances of the following exception. Need to investigate and resolve.

```
ERROR [2016-09-07 19:59:53,136] io.rapidpro.mage.twitter.TwitterStream: Exception in Twitter stream
! twitter4j.JSONException: JSONObject["percent_full"] not found.
! at twitter4j.JSONObject.get(JSONObject.java:391) ~[mage.jar:0.1.78]
! at twitter4j.JSONObject.getInt(JSONObject.java:429) ~[mage.jar:0.1.78]
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient.processStallWarning(BaseTwitter4jClient.java:255) ~[mage.jar:0.1.78]
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient.processMessage(BaseTwitter4jClient.java:215) ~[mage.jar:0.1.78]
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient.parseMessage(BaseTwitter4jClient.java:129) ~[mage.jar:0.1.78]
! at com.twitter.hbc.twitter4j.BaseTwitter4jClient$1.run(BaseTwitter4jClient.java:76) ~[mage.jar:0.1.78]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
```

**Comment by rowanseymour** [comment]
This is a bug in the not-so-maintained-any-longer Twitter HBC library https://github.com/twitter/hbc/issues/155

**Comment by ericnewcomer** [comment]
What's the net effect to us? Does this cause us to miss messages? We should probably fork and fix it as long as we depend on this library.

**Comment by rowanseymour** [comment]
No effect - happens during creation of a stream to a user with a high number of followers (Twitter sends us FOLLOWS_OVER_LIMIT packet), but stream creation succeeds and we get the DMs.

Agreed we should still fix this - it's been on my todo list forever.

**Comment by ericnewcomer** [comment]
Ya, I can see why that has lingered then! :neckbeard:
